name: GitHub Snake Game - Custom White Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation - White Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-white.svg?color_snake=white&color_dots=#c0c0c0,#d3d3d3,#e0e0e0,#f0f0f0,#ffffff
            dist/github-snake-white.gif?color_snake=white&color_dots=#c0c0c0,#d3d3d3,#e0e0e0,#f0f0f0,#ffffff&palette=github-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update white snake animation [skip ci]"
